### ISSUE TITLE
Surface Pro 2017 (gen 5) left right reversed

### ISSUE THREAD

**Issue by tarmack** [linux-surface/iptsd#1]
First of all big props for making this!!

When testing it was immediately apparent that the coordinates from left to right are reversed. I also noticed that the position of the cursor is spot on on the top of the screen but seems to build up about a centimeter of error and can not reach the bottom of the screen.

Some general feedback: In the readme it is mentioned that the tracking can be erratic sometimes, I noticed that it is pretty good but the cursor get jittery when the touch area gets bigger (like with a thumb).

Device SKU: Surface_Pro_1796

**Comment by StollD** [comment]
Thank you for testing!

> I also noticed that the position of the cursor is spot on on the top of the screen but seems to build up about a centimeter of error and can not reach the bottom of the screen.

I pushed a commit that should fix this. I already noticed that sometimes the input was a bit offset when being near the screen, but I never had the idea to check if areas are unreachable. Thanks for noticing.

> When testing it was immediately apparent that the coordinates from left to right are reversed.

Yeah, thats going to be a bit annoying. Basically, all the surfaces have different orientations for the touch sensor. There is no real way to get this information from the device, because in Windows they simply have different binary firmwares where these details are adjusted.

For the moment what you can do is add `x = float32(hm.Width) - (x + 1)` above this line: https://github.com/linux-surface/iptsd/blob/master/processing/heatmap.go#L106. That should invert the x-axis, just like the y-axis already gets inverted.

Could you post the vendor / device ID for your device? It's the `0123:4567` number that will be printed when you run iptsd. Then I can add some code to properly detect these quirks.

**Comment by tarmack** [comment]
> For the moment what you can do is add x = float32(hm.Width) - (x + 1) above this line: 
I already did, and it works perfectly. :-)

The patch for the offset also fixes the problem there.

The device ID is: 1b96:001f

**Comment by StollD** [comment]
Thanks! I added the for quirking specific devices to master, so now the daemon should detect SP5s / SB2s and adjust the axes accordingly.

**Comment by tarmack** [comment]
Works as advertised, thank you.
