### ISSUE TITLE
[SP7] Laggy pen detection for handwriting

### ISSUE THREAD

**Issue by Emporea** [linux-surface/iptsd#125]
I am using Xournal++ with surface kernel and iptsd 1.2.0 (clean install today, no old configs) on fedora 38 on a surface pro 7.

Thank you for all your hard work. I appreciate it.

But I reinstalled Windows 10 and 11 yesterday for the lulz and noticed again how much smoother the pen detection is on windows (everything else is super slow though... still windows obv.. :D ).

Back to Fedora today
---

If I run `sudo iptsd-show (iptsd-find-hidraw)`, I can clearly see that the "where" marker has a pretty high delay, so it moves behind the actual pen when I write. This is not a pleasant sensation, and unfortunately Windows does a much better job at this (obviously because of the proprietary drivers) ....

Is there any way to speed up this detection, or do we have to live with the delay?

(Or are there other configuration options to make it faster that I have missed so far?)

**Comment by StollD** [comment]
There are multiple layers to this issue:

* The linux driver for IPTS has to do polling because of how the hardware was designed around being used together with the GPU. A microcontroller in the GPU basically polls all the time, and schedules processing on the GPU when data arrives. On the main CPU we can't poll all the time, so we need to accept some latency.
* Before the inputs arrive at an application, the data is sent to userspace, processed there, and then sent back to kernelspace through uinput. Every switch between kernel- and userspace takes time and adds latency. With the proprietary driver, the data never leaves kernelspace before inputs are sent to the applications.
* Applications themselves can have a certain latency, because of how they render or receive inputs.

Another important point is that the hardware itself has latency. Windows tries to hide it by using predictive algorithms, but this AFAIK is only done in some apps (e.g. OneNote). You can find reports on e.g. Reddit where people report that they have similar latency in Photoshop, but no latency in OneNote.

For more information, check this issue: https://github.com/linux-surface/linux-surface/issues/1061
