### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by tmarkov** [linux-surface/iptsd#14]
Hi, can we list and prioritize missing features for iptsd along with some basic specs for them?

**Comment by StollD** [comment]
I think the only feature that is actually missing is contact area / pressure calculation. The docs for the Linux multitouch protocol describe how that data needs to be reported: https://www.kernel.org/doc/html/latest/input/multi-touch-protocol.html.

We obviously still need to figure out the support for Gen7 devices, but that's more of a kernel side question, and not really something that's missing from iptsd.

And obviously improving / fine tuning / fixing the current touch detection calculations, if that turns out to be necessary (doesn't seem to be for me, but let's see what reports come in from users now that it is the default).

**Comment by qzed** [comment]
I still have the issue that when I press harder, my touch gets misclassified as palm (or rather I think that that's what's happening). Having a config option for the threshold(s?) there would be nice. Apart from that, I'm in favor of adding config options for basically everything. Could even make sense to add one for the driver refresh/doorbell-check rate (although that would require changes in the driver).

**Comment by qzed** [comment]
And there's also still some jitter and drift when I try to pinch-to-zoom-and-rotate in krita.

Finger-tracking also doesn't seem to be completely reliable, but that could also be my finger getting misclassified and touch being dropped from that and the index assigned to the other finger (basically, if I pinch-to-zoom-and-rotate with one finger hitting the screen first so that it draws instead of zoom/rotate, I sometimes get a straight line from one finger to the other). We might want to introduce a threshold for maximum finger motion in one frame, i.e. if it's over that threshold, it's a new index. Also thinking about this, what is happening when a finger gets released/classified as palm? The index of any other fingers probably shouldn't change due to that (I think such a change could also cause that problem in krita).

That thing could, of course, also be a problem in Krita, so we should also consider having some sort of simple debug application that shows you your fingers on screen with basic stats, such as index.
