### ISSUE TITLE
Idle power usage

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/iptsd#23]
In `powertop`, `iptsd` is using ~1W of power even when I'm not using my tablet. This is around 12% of the total idle power usage. I see `iptsd` in `htop` constantly using 1.3% CPU when idle. It would be nice if battery life could be improved by making `iptsd` more efficient.

This is when my tablet is completely inactive. I have my brightness lowered to the minimum so that the screen is completely black. I'm also not touching the screen at all. I would have expected about 0% CPU usage in this case as there is no input to process.

```
  1.56 W      4.0 ms/s     394.3        Process        [PID 933] /usr/bin/iptsd
```

### Environment

- Hardware model: `Surface Pro 7 i7 512GB`
- Kernel version: `Linux daniel-tablet1 5.9.8-surface #1 SMP Fri Nov 13 21:49:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: `Ubuntu 20.04.1 LTS Desktop`

```
$ apt-cache policy iptsd
iptsd:
  Installed: 0.2.1-1
  Candidate: 0.2.1-1
  Version table:
 *** 0.2.1-1 500
        500 https://pkg.surfacelinux.com/debian release/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by StollD** [comment]
Could you try it with the version from master? Since the last release we switched from the Go version to a version written in C, which should hopefully reduce resource usage by the daemon. 

Unfortunately it is not really possible to remove all idle usage, because of how the IPTS hardware works. We need to poll it constantly and check if it has new data for us. The more we poll, the faster it responds to inputs, but then it will also use more resources. If you poll less you will use less resources, but the touchscreen will feel really janky.

**Comment by danielzgtg** [comment]
I tested it at 326f792.

> hopefully reduce resource usage

The idle CPU usage has improved. It went from around 3.3% to around 0.7% - 1.3% in `htop`. `powertop` shows a similar improvement:
```
189 mW      1.4 ms/s      47.3        Process        [PID 11318] build/iptsd
```

This looks just like the idle CPU usage in Windows. Even if it was still higher, it is now lower than or similar to that of the bunch of other processes I have running.

> Unfortunately it is not really possible to remove all idle usage, [...]. We need to poll it [...]

We could move this to kernelspace and only wake up userspace when there is new data. It could also be integrated with the display driver to stop when the brightness is zero.

However, that has its own tradeoffs and might be too complicated.
Closing this issue as the factor of 3 improvement means that the power usage is now imperceptible compared to other things
