### ISSUE TITLE
Port to Rust

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/iptsd#6]
On IRC a while ago, it was suggested that this project be ported from Go to Rust.

Are there still plans to do so?

**Comment by StollD** [comment]
iirc @archseer was interested in doing a Rust port, to see how the performance difference would look like. But since then a lot of additional code has been written, which means the amount of work that is required for a port has increased too.

If anyone wants to work on a port, and needs some help with understanding the current code, I'm happy to help. I don't have any experience with Rust, so I can't help with the actual port itself.

I don't think that a port is *needed* though. I can't really imagine that there would be a big difference between a Rust version and the Go one. Still though, if anyone really wants to do it, I would be curious about how that difference would actually look like.

**Comment by StollD** [comment]
I'm going to close this one for now. If anyone wants to work on a rust port, we can reopen it.

**Comment by qzed** [comment]
I'd have a look at it when I'm done with the SAM if nobody has done that by then. But that'll probably still take a while.
