### ISSUE TITLE
Touch input does not rotate with screen orientation

### ISSUE THREAD

**Issue by groengpx** [linux-surface/iptsd#69]
When rotating the screen (via auto rotation), the touch inputs are not rotated.

For example, a swipe to the right is now a swipe down.

- Device: Surface Pro 7+
- iptsd @ https://github.com/linux-surface/iptsd/commit/b9a1f1f66a42af350f3def66616be2891ac41e6e
- ithc @ https://github.com/quo/ithc-linux/commit/02bf0eb009dcb6d037a1c10bd70e7fb5d29718bb
- OS: Ubuntu 20.04 (Focal Fossa), with an otherwise default linux-surface setup
- Shell: Gnome (vanilla, not the Ubuntu variant)

**Comment by StollD** [comment]
Are you using Wayland or X11?

I can not reproduce this on an SB2 with Fedora 36 and Gnome Wayland.

We had a similar issue at some point (with the old IPTS driver) where Gnome would get confused, because there were two seperate touchscreen devices, the one for multitouch and the one for singletouch. When you rotated the screen, it would only rotate the first device, which was the singletouch device. We solved it by removing singletouch support from the driver...

I wonder if this issue could be related.

**Comment by groengpx** [comment]
Ah, sorry, forgot to check. Yes, X11 indeed. When switching to Wayland, the problem goes away.
