### ISSUE TITLE
Calibrating Touch Screen on Surface Pro 5 (SP5) not working

### ISSUE THREAD

**Issue by ArPhil** [linux-surface/iptsd#94]
Hi,

I tried to follow the instructions provided on the [wiki] (https://github.com/linux-surface/iptsd/wiki/Calibrating-iptsd) for calibrating the touchscreen. I noticed, that neither the `iptsd-find-hidraw` nor the `iptsd-calibrate` binaries are available on my system:

Linux surfux 6.0.6-surface #1 SMP PREEMPT_DYNAMIC Thu Nov 3 13:54:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian 

I installed iptsd from the linux-surface repository as instructed ([see here](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#debian--ubuntu)), so it looks the required binaries do NOT come with the iptsd package via `sudo apt install iptsd`.

As alternative, I uninstalled iptsd via `sudo apt purge iptsd` and installed the lasted iptsd build as described [here](https://github.com/linux-surface/iptsd#installing) via `sudo dpkg -i iptsd_0.5.1-1_amd64.deb`. So the above mentioned binaries are availabe now, but `iptsd-find-hidraw` returns nothing / empty string and therefore I cannot exectue `iptsd-calibrate` since it expects the ID.

**What is the proper way of calibrating the touchscreen when iptsd has been installed via the linux-surface repository?**

Any help is highly appreciated! :-)

**Comment by StollD** [comment]
Yes, these are only there if you build iptsd from the master branch. In which case you also need to build and install the IPTS kernel driver from source (https://github.com/linux-surface/intel-precise-touch).

I will make this more clear in the wiki page, sorry.

Calibrating the iptsd from the repository isnt really possible because its a very old version of iptsd, where a lot of variables are hardcoded (and some check for palm rejection are actually broken iirc). I am working on getting the code in the master branch ready for a release but its still not quite there yet.

**Comment by ArPhil** [comment]
@StollD , thanks for taking the time and the rapid feedback! That now explains to me, why some of the changes I did in `/etc/ipts.conf` did not show any effects on my Surface, since I used the repository version of iptsd. I will try to build and install the IPTS kernel driver from source on occasion.

Again, thanks for all the great work and effort! 😃
