### ISSUE TITLE
In sleep mode the hid device gets lost

### ISSUE THREAD

**Issue by LegacyGamerHD** [linux-surface/iptsd#95]
![IMG_20221107_115831464_HDR](https://user-images.githubusercontent.com/25864932/200297930-65d1c40a-5035-43d9-aed3-c8d79f00d8b0.jpg)
![IMG_20221107_115857396_HDR](https://user-images.githubusercontent.com/25864932/200297975-ce979dfe-aead-4c44-89ef-6357ff6f46fa.jpg)

I will get more info if asked 

This is on bliss os surface build

**Comment by StollD** [comment]
This is expected. The lifetime of the iptsd service needs to be bound to the lifetime of the device, because the device ID is not stable and may change between reloads of the kernel driver (which happen during suspend / resume). Its the reason why the systemd service setup of iptsd is a bit unconventional.

On systems without systemd this can probably be done using the iptsd-find-hidraw script and udev (manually starting and stopping the service on device creation / removal).
